In [1]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)

In [5]:
print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [7]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
## Matrizes
matriz_zeros = np.zeros((3,4))
print(matriz_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
## Notas de alunos

lista_de_notas = [9.8, 7.5, 9.6, 8.8, 7.7]

notas = np.array(lista_de_notas)

In [23]:
print("Máximo: ", notas.max())
print("Minimo: ", notas.min())
print("Desvio padrão: ", notas.std())
print("Média: ", notas.mean())
print("Posição do menor: ", notas.argmin())

Máximo:  9.8
Minimo:  7.5
Desvio padrão:  0.9453041838477179
Média:  8.680000000000001
Posição do menor:  1
